package dao;

import com.banking.dao.AccountDAO;
import com.banking.db.DatabaseConfig;
import com.banking.model.*; // Import all model classes

import java.sql.Connection;
import java.sql.SQLException;

/**
 * Main application entry point demonstrating system functionality and JDBC integration.
 * This class correctly uses Dependency Injection for the DAO layers and demonstrates CRUD operations.
 */
public class BankingSystemDemo {

    public static void main(String[] args) {

        System.out.println("--- Banking System Simulation Start ---");

        // --- 1. Initialization and Dependency Injection ---

        // 1a. Initialize independent DAO first
        CustomerDAO customerDao = new CustomerDAO();

        // 1b. Initialize dependent DAO using DI (AccountDAO needs CustomerDAO)
        AccountDAO accountDao = new AccountDAO(customerDao);

        // 2. Setup and Connection Check

        // Prints the necessary SQL for manual setup in phpMyAdmin
        accountDao.setupDatabaseSchema();

        // Ensure connection is possible (Resource management improvement)
        try (Connection conn = DatabaseConfig.getConnection()) {
            if (conn != null) {
                System.out.println("✅ Database connection successful! Proceeding with logic.");
            }
        } catch (SQLException e) {
            System.err.println("❌ Database connection failed.");
            System.err.println("   Ensure XAMPP MySQL is running, and the 'banking_system' database exists.");
            System.err.println("   Error details: " + e.getMessage());
            return; // Exit if the connection fails
        }

        Bank firstNational = new Bank("First National Bank of Gabs");

        // Customer 1: Ms. Alice
        Customer alice = new Customer("C001", "Alice", "Smith", "101 Main St");
        if(customerDao.save(alice)) {
            System.out.println("\nDB: Customer 'Alice' saved successfully.");
        }

        System.out.println("\n--- 3. Account Opening and Initial Persistence ---");

        // Open and save accounts (using unique account numbers generated by Bank)
        SavingsAccount aliceSavings = firstNational.openAccount(alice, "Gaborone Central");
        if(accountDao.save(aliceSavings)) {
            System.out.println("DB: Savings Account saved (ID: " + aliceSavings.getAccountNumber() + ")");
        }

        // ChequeAccount requires ChequeDetails to be saved in a separate table, handled by AccountDAO.save()
        ChequeAccount aliceCheque = firstNational.openAccount(alice, "Gaborone Central", "TechCorp Ltd", "1 Business Park");
        if(accountDao.save(aliceCheque)) {
            System.out.println("DB: Cheque Account saved (ID: " + aliceCheque.getAccountNumber() + ")");
        }

        // Assuming InvestmentAccount uses base table fields only
        InvestmentAccount aliceInvestment = firstNational.openAccount(alice, "Gaborone Central", 10000.00);
        if(accountDao.save(aliceInvestment)) {
            System.out.println("DB: Investment Account saved (ID: " + aliceInvestment.getAccountNumber() + ")");
        }

        System.out.println("\n--- 4. Transactions and DB Update ---");

        // Transaction: Deposit
        double depositAmount = 5000.00;
        aliceCheque.deposit(depositAmount);
        System.out.println("STATE: Deposited $" + depositAmount + " to Cheque. New balance: $" + aliceCheque.getBalance());

        // JDBC persistence: Update DB with the new balance
        if (accountDao.updateBalance(aliceCheque.getAccountNumber(), aliceCheque.getBalance())) {
            System.out.println("DB: Balance updated for " + aliceCheque.getAccountNumber());
        }

        // Transaction: Withdrawal
        double withdrawAmount = 500.00;
        aliceInvestment.withdraw(withdrawAmount);
        System.out.println("STATE: Withdrew $" + withdrawAmount + " from Investment. New balance: $" + aliceInvestment.getBalance());

        // JDBC persistence: Update DB with the new balance
        accountDao.updateBalance(aliceInvestment.getAccountNumber(), aliceInvestment.getBalance());


        System.out.println("\n--- 5. Verify Persistence (READ Operation) ---");

        // This confirms the complex AccountDAO.findByAccountNumber logic works and retrieves subclass details
        Account retrievedAccount = accountDao.findByAccountNumber(aliceCheque.getAccountNumber());

        if (retrievedAccount != null) {
            System.out.println("DB READ SUCCESS: Account retrieved by number (" + retrievedAccount.getAccountNumber() + ")");
            System.out.println(" - Type Check: Is ChequeAccount? " + (retrievedAccount instanceof ChequeAccount));
            if (retrievedAccount instanceof ChequeAccount ca) {
                System.out.println(" - Cheque Details: Employer is " + ca.getEmployerName());
            }
            System.out.println(" - Retrieved Balance: $" + retrievedAccount.getBalance() + " (Should match deposited amount)");
        } else {
            System.err.println("DB READ FAILURE: Could not retrieve account " + aliceCheque.getAccountNumber());
        }

        System.out.println("\n--- 6. Interest Calculation and Final DB Update (Polymorphism) ---");

        // Calculate interest (updates object state based on account type)
        firstNational.calculateMonthlyInterest();

        // After interest, update the affected account balances in the database
        accountDao.updateBalance(aliceSavings.getAccountNumber(), aliceSavings.getBalance());
        accountDao.updateBalance(aliceInvestment.getAccountNumber(), aliceInvestment.getBalance());

        System.out.println("\n--- Final Balances in System State ---");
        System.out.println(aliceSavings);
        System.out.println(aliceInvestment);
        System.out.println(aliceCheque);
    }
}
